CC = gcc
RM = rm -f

CFLAGS = -std=c99 -pedantic -Wall -O2
PKGS = `pkg-config --libs --cflags gtk+-3.0 liblightdm-gobject-1 gmodule-export-2.0`
LIBS = `pkg-config --libs gtk+-3.0 liblightdm-gobject-1 gmodule-export-2.0`

TARGET = lightdm-matrix-greeter
.PHONY: all


all: $(TARGET)

$(TARGET):matrix_greeter.o
	$(CC) -o $@ $^ $(LIBS)

matrix_greeter.o: matrix_greeter.c config.h
	$(CC) $(CFLAGS) -c $^ $(PKGS)

install:
	$(shell mkdir -p /usr/share/xgreeters)
	cp lightdm-matrix-greeter.desktop /usr/share/xgreeters/lightdm-matrix-greeter.desktop
	cp lightdm-matrix-greeter $(PREFIX)/bin/lightdm-matrix-greeter

uninstall:
	$(RM) /usr/share/xgreeters/lightdm-matrix-greeter.desktop
	$(RM) $(PREFIX)/bin/lightdm-matrix-greeter


clean:
	$(RM) *.o
