/* automatically generated from matrix_lightdm_greeter.ui */
#ifdef __SUNPRO_C
#pragma align 4 (lightdm_gtk_greeter_ui)
#endif
#ifdef __GNUC__
static const char lightdm_gtk_greeter_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char lightdm_gtk_greeter_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><object class=\"GtkDialog\" id=\"matrix_dialog_c"
  "ommand\"><property name=\"name\">matrix_dialog_command</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"modal\">True</pr"
  "operty><property name=\"default_width\">275</property><property name=\""
  "default_height\">130</property><property name=\"type_hint\">dialog</pro"
  "perty><child type=\"titlebar\"><placeholder/></child><child internal-ch"
  "ild=\"vbox\"><object class=\"GtkBox\" id=\"matrix_dialog_command_box\">"
  "<property name=\"name\">matrix_dialog_command_box</property><property n"
  "ame=\"can_focus\">False</property><property name=\"orientation\">vertic"
  "al</property><property name=\"spacing\">1</property><child internal-chi"
  "ld=\"action_area\"><object class=\"GtkButtonBox\" id=\"matrix_dialog_co"
  "mmand_button_box\"><property name=\"name\">matrix_dialog_command_button"
  "_box</property><property name=\"can_focus\">False</property><property n"
  "ame=\"layout_style\">end</property><child><object class=\"GtkButton\" i"
  "d=\"matrix_dialog_command_action_button\"><property name=\"name\">matri"
  "x_dialog_command_action_button</property><property name=\"label\" trans"
  "latable=\"yes\">button</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"receiv"
  "es_default\">True</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkButt"
  "on\" id=\"matrix_dialog_command_button_cancel\"><property name=\"name\""
  ">matrix_dialog_command_button_cancel</property><property name=\"label\""
  " translatable=\"yes\">button</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property></object><packing><property name=\"ex"
  "pand\">True</property><property name=\"fill\">True</property><property "
  "name=\"position\">1</property></packing></child></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">0</property></packing></child><child>"
  "<object class=\"GtkLabel\" id=\"matrix_dialog_info_label\"><property na"
  "me=\"name\">matrix_dialog_info_label</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label\" translatable=\"yes\">label</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">True"
  "</property><property name=\"padding\">13</property><property name=\"pos"
  "ition\">1</property></packing></child></object></child><action-widgets>"
  "<action-widget response=\"0\">matrix_dialog_command_action_button</acti"
  "on-widget><action-widget response=\"1\">matrix_dialog_command_button_ca"
  "ncel</action-widget></action-widgets></object><object class=\"GtkWindow"
  "\" id=\"matrix_greeter_window\"><property name=\"name\">matrix_greeter_"
  "window</property><property name=\"can_focus\">False</property><child ty"
  "pe=\"titlebar\"><placeholder/></child><child><object class=\"GtkOverlay"
  "\" id=\"matrix_greeter_overlay\"><property name=\"name\">matrix_greeter"
  "_overlay</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><child><object class=\"GtkBox\" id=\""
  "matrix_box_container\"><property name=\"name\">matrix_box_container</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"valign\">baseline</property><pr"
  "operty name=\"vexpand\">True</property><property name=\"orientation\">v"
  "ertical</property><property name=\"baseline_position\">bottom</property"
  "><child><object class=\"GtkBox\" id=\"matrix_header_box\"><property nam"
  "e=\"name\">matrix_header_box</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "orientation\">vertical</property><child><object class=\"GtkImage\" id=\""
  "matrix_header_logo\"><property name=\"name\">matrix_header_logo</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"ypad\">5</property><property name=\""
  "pixel_size\">68</property><property name=\"icon_name\">computer</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkLabel\" id=\"matrix_hostnam"
  "e_label\"><property name=\"name\">matrix_hostname_label</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">[HostName]</pr"
  "operty><property name=\"width_chars\">15</property><property name=\"max"
  "_width_chars\">100</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">1</property></packing></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">0</property></packing></child><child><objec"
  "t class=\"GtkBox\" id=\"matrix_login_box\"><property name=\"name\">matr"
  "ix_login_box</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"orientation\">v"
  "ertical</property><child><object class=\"GtkBox\" id=\"matrix_login_inp"
  "ut_box\"><property name=\"name\">matrix_login_input_box</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"halign\">center</property><property name=\""
  "valign\">end</property><child><object class=\"GtkLabel\" id=\"matrix_in"
  "put_label\"><property name=\"name\">matrix_input_label</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">[prompt_input]<"
  "/property><property name=\"ellipsize\">end</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkEntry\" id=\"matrix_user_entry\"><property name="
  "\"name\">matrix_user_entry</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property></object><packing><"
  "property name=\"expand\">False</property><property name=\"fill\">True</"
  "property><property name=\"position\">1</property></packing></child></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">True</property><property name=\"position\">0</property></packi"
  "ng></child><child><object class=\"GtkLabel\" id=\"matrix_response_label"
  "\"><property name=\"name\">matrix_response_label</property><property na"
  "me=\"name\">matrix_response_label</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"label\" translatable=\"yes\">[response_label]</property></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">True</property><property name=\"position\">1</property></packing></"
  "child></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">1</proper"
  "ty></packing></child><child><object class=\"GtkBox\" id=\"matrix_comman"
  "d_box\"><property name=\"name\">matrix_command_box</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"halign\">center</property><property name=\"valig"
  "n\">baseline</property><property name=\"baseline_position\">bottom</pro"
  "perty><child><object class=\"GtkButton\" id=\"matrix_shutdown_button\">"
  "<property name=\"name\">matrix_shutdown_button</property><property name"
  "=\"label\" translatable=\"yes\">shutdown</property><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"receives_default\">True</property><property name=\"halign\""
  ">center</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkButton\" id="
  "\"matrix_restart_button\"><property name=\"name\">matrix_restart_button"
  "</property><property name=\"label\" translatable=\"yes\">restart</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">True</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">True</property><property name=\"position\">1</property></pa"
  "cking></child><child><object class=\"GtkButton\" id=\"matrix_hibernate_"
  "button\"><property name=\"name\">matrix_hibernate_button</property><pro"
  "perty name=\"label\" translatable=\"yes\">hibernate</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">True</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">2</property></packing></child"
  "><child><object class=\"GtkButton\" id=\"matrix_sleep_button\"><propert"
  "y name=\"name\">matrix_sleep_button</property><property name=\"label\" "
  "translatable=\"yes\">sleep</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">False</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">True</property><property "
  "name=\"position\">3</property></packing></child></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">35</property></packing></child></objec"
  "t><packing><property name=\"index\">-1</property></packing></child></ob"
  "ject></child></object></interface>"
};

static const unsigned lightdm_gtk_greeter_ui_length = 9396u;

