/* automatically generated from matrix_lightdm_greeter.ui */
#ifdef __SUNPRO_C
#pragma align 4 (lightdm_gtk_greeter_ui)
#endif
#ifdef __GNUC__
static const char lightdm_gtk_greeter_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char lightdm_gtk_greeter_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><object class=\"GtkDialog\" id=\"matrix_dialog_c"
  "ommand\"><property name=\"name\">matrix_dialog_command</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"modal\">True</pr"
  "operty><property name=\"default_width\">275</property><property name=\""
  "default_height\">130</property><property name=\"type_hint\">dialog</pro"
  "perty><child type=\"titlebar\"><placeholder/></child><child internal-ch"
  "ild=\"vbox\"><object class=\"GtkBox\" id=\"matrix_dialog_command_box\">"
  "<property name=\"name\">matrix_dialog_command_box</property><property n"
  "ame=\"can_focus\">False</property><property name=\"orientation\">vertic"
  "al</property><property name=\"spacing\">1</property><child internal-chi"
  "ld=\"action_area\"><object class=\"GtkButtonBox\" id=\"matrix_dialog_co"
  "mmand_button_box\"><property name=\"name\">matrix_dialog_command_button"
  "_box</property><property name=\"can_focus\">False</property><property n"
  "ame=\"margin_bottom\">8</property><property name=\"layout_style\">end</"
  "property><child><object class=\"GtkButton\" id=\"matrix_dialog_command_"
  "action_button\"><property name=\"name\">matrix_dialog_command_action_bu"
  "tton</property><property name=\"label\" translatable=\"yes\">button</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"receives_default\">True</propert"
  "y><property name=\"margin_left\">5</property></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkButton\" id=\"matrix_dialog_command_button_cancel\"><prop"
  "erty name=\"name\">matrix_dialog_command_button_cancel</property><prope"
  "rty name=\"label\" translatable=\"yes\">button</property><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"receives_default\">True</property><property name=\"ma"
  "rgin_left\">15</property><property name=\"margin_right\">7</property></"
  "object><packing><property name=\"expand\">True</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkLabel\" id=\"matr"
  "ix_dialog_info_label\"><property name=\"name\">matrix_dialog_info_label"
  "</property><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"label\" translatable=\"yes\""
  ">label</property></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">True</property><property name=\"padding\""
  ">13</property><property name=\"position\">1</property></packing></child"
  "></object></child><action-widgets><action-widget response=\"0\">matrix_"
  "dialog_command_action_button</action-widget><action-widget response=\"1"
  "\">matrix_dialog_command_button_cancel</action-widget></action-widgets>"
  "</object><object class=\"GtkWindow\" id=\"matrix_greeter_window\"><prop"
  "erty name=\"name\">matrix_greeter_window</property><property name=\"can"
  "_focus\">False</property><child type=\"titlebar\"><placeholder/></child"
  "><child><object class=\"GtkOverlay\" id=\"matrix_greeter_overlay\"><pro"
  "perty name=\"name\">matrix_greeter_overlay</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><c"
  "hild><object class=\"GtkBox\" id=\"matrix_box_container\"><property nam"
  "e=\"name\">matrix_box_container</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"valign\">baseline</property><property name=\"vexpand\">True</proper"
  "ty><property name=\"orientation\">vertical</property><property name=\"s"
  "pacing\">124</property><property name=\"baseline_position\">bottom</pro"
  "perty><child><object class=\"GtkBox\" id=\"matrix_header_box\"><propert"
  "y name=\"name\">matrix_header_box</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"orientation\">vertical</property><child><object class=\"GtkImage\""
  " id=\"matrix_header_logo\"><property name=\"name\">matrix_header_logo</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"margin_top\">17</property><pr"
  "operty name=\"ypad\">5</property><property name=\"pixel_size\">68</prop"
  "erty><property name=\"icon_name\">computer</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkLabel\" id=\"matrix_hostname_label\"><property n"
  "ame=\"name\">matrix_hostname_label</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">[HostName]</property><property name"
  "=\"width_chars\">15</property><property name=\"max_width_chars\">100</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">1</prop"
  "erty></packing></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">0</property></packing></child><child><object class=\"GtkBox\" i"
  "d=\"matrix_login_box\"><property name=\"name\">matrix_login_box</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"orientation\">vertical</property><c"
  "hild><object class=\"GtkBox\" id=\"matrix_login_input_box\"><property n"
  "ame=\"name\">matrix_login_input_box</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"halign\">center</property><property name=\"valign\">end</propert"
  "y><property name=\"margin_top\">14</property><child><object class=\"Gtk"
  "Label\" id=\"matrix_input_label\"><property name=\"name\">matrix_input_"
  "label</property><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"margin_right\">12</pro"
  "perty><property name=\"label\" translatable=\"yes\">[prompt_input]</pro"
  "perty><property name=\"ellipsize\">end</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">0</property></packing></child><child>"
  "<object class=\"GtkEntry\" id=\"matrix_user_entry\"><property name=\"na"
  "me\">matrix_user_entry</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkLabel\" id=\"matrix_response_label\"><"
  "property name=\"name\">matrix_response_label</property><property name=\""
  "name\">matrix_response_label</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "margin_top\">10</property><property name=\"label\" translatable=\"yes\""
  ">[response_label]</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">1</property></packing></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">1</property></packing></child><child><objec"
  "t class=\"GtkBox\" id=\"matrix_command_box\"><property name=\"name\">ma"
  "trix_command_box</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"halign\">ce"
  "nter</property><property name=\"valign\">baseline</property><property n"
  "ame=\"margin_top\">10</property><property name=\"margin_bottom\">8</pro"
  "perty><property name=\"baseline_position\">bottom</property><child><obj"
  "ect class=\"GtkButton\" id=\"matrix_shutdown_button\"><property name=\""
  "name\">matrix_shutdown_button</property><property name=\"label\" transl"
  "atable=\"yes\">shutdown</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">True</property><property name=\"halign\">center</property"
  "><property name=\"margin_right\">21</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkButton\" id=\"matrix_restart_button\"><property name=\""
  "name\">matrix_restart_button</property><property name=\"label\" transla"
  "table=\"yes\">restart</property><property name=\"name\">matrix</propert"
  "y><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">True</property><property name=\"position\">1</property></packi"
  "ng></child><child><object class=\"GtkButton\" id=\"matrix_hibernate_but"
  "ton\"><property name=\"name\">matrix_hibernate_button</property><proper"
  "ty name=\"label\" translatable=\"yes\">hibernate</property><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"receives_default\">True</property><property name=\""
  "margin_left\">21</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">True</property><property name=\""
  "position\">2</property></packing></child><child><object class=\"GtkButt"
  "on\" id=\"matrix_sleep_button\"><property name=\"name\">matrix_sleep_bu"
  "tton</property><property name=\"label\" translatable=\"yes\">sleep</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">True</property"
  "><property name=\"margin_left\">21</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">3</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">35</property></packing></ch"
  "ild></object><packing><property name=\"index\">-1</property></packing><"
  "/child></object></child></object></interface>"
};

static const unsigned lightdm_gtk_greeter_ui_length = 10018u;

