/* automatically generated from matrix_lightdm_greeter.ui */
#ifdef __SUNPRO_C
#pragma align 4 (lightdm_gtk_greeter_ui)
#endif
#ifdef __GNUC__
static const char lightdm_gtk_greeter_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char lightdm_gtk_greeter_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><object class=\"GtkWindow\" id=\"matrix_greeter_"
  "window\"><property name=\"can_focus\">False</property><child type=\"tit"
  "lebar\"><placeholder/></child><child><object class=\"GtkOverlay\" id=\""
  "matrix_greeter_overlay\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><child><object class=\"GtkBox\""
  " id=\"matrix_box_container\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"vexpand\""
  ">True</property><property name=\"orientation\">vertical</property><prop"
  "erty name=\"spacing\">200</property><property name=\"baseline_position\""
  ">center</property><child><object class=\"GtkBox\" id=\"matrix_header_bo"
  "x\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"orientation\">vertical</property><"
  "child><object class=\"GtkImage\" id=\"matrix_header_logo\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"margin_top\">17</property><property name=\"ypad\">"
  "5</property><property name=\"pixel_size\">68</property><property name=\""
  "icon_name\">computer</property></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">True</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kLabel\" id=\"matrix_hostname_label\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">[HostName]</property><property name=\"widt"
  "h_chars\">15</property><property name=\"max_width_chars\">100</property"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkBox\" id=\"mat"
  "rix_login_box\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"orientation\">vertical"
  "</property><child><object class=\"GtkBox\" id=\"matrix_login_input_box\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"halign\">center</property><property n"
  "ame=\"valign\">end</property><property name=\"margin_top\">14</property"
  "><child><object class=\"GtkLabel\" id=\"matrix_input_label\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"margin_right\">12</property><property name=\"lab"
  "el\" translatable=\"yes\">[prompt_input]</property><property name=\"ell"
  "ipsize\">end</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">0</property></packing></child><child><object class=\"GtkEntry\""
  " id=\"matrix_user_entry\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">1</property></packing></child></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkLabel\" id=\"matrix_response_label\"><propert"
  "y name=\"name\">matrix_response_label</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"margin_top\">10</property><property name=\"label\" translatab"
  "le=\"yes\">[response_label]</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">1</property></packing></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"position\">1</property></packing></child><ch"
  "ild><object class=\"GtkBox\" id=\"matrix_command_box\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"halign\">center</property><property name=\"valign\">cen"
  "ter</property><property name=\"margin_top\">23</property><property name"
  "=\"margin_bottom\">15</property><child><object class=\"GtkButton\" id=\""
  "matrix_shutdown_button\"><property name=\"label\" translatable=\"yes\">"
  "shutdown</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">T"
  "rue</property><property name=\"halign\">center</property><property name"
  "=\"margin_right\">21</property></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">True</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kButton\" id=\"matrix_restart_button\"><property name=\"label\" transla"
  "table=\"yes\">restart</property><property name=\"name\">matrix</propert"
  "y><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">True</property><property name=\"position\">1</property></packi"
  "ng></child><child><object class=\"GtkButton\" id=\"matrix_hibernate_but"
  "ton\"><property name=\"label\" translatable=\"yes\">hibernate</property"
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property><pro"
  "perty name=\"margin_left\">21</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">2</property></packing></child><child><object c"
  "lass=\"GtkButton\" id=\"matrix_sleep_button\"><property name=\"label\" "
  "translatable=\"yes\">sleep</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"margin_left\">21</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">3</propert"
  "y></packing></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">2</property></packing></child></object><packing><property name=\"i"
  "ndex\">-1</property></packing></child></object></child></object></inter"
  "face>"
};

static const unsigned lightdm_gtk_greeter_ui_length = 6236u;

